### PR TITLE
Use full covariance matrix when taking weighted mean of `Measurement`s

### LINKED ISSUE #8: Shift between MSWD calculated with Isoplot.jl and IsoplotR
Hi, 

I've observed a difference that I don't think is negligeable between MSWD calculated for wmean from Isoplot.jl and IsoplotR. I looked at the code here and have no issue with the way it is implemented in this package but I would like to understand what could be the reason for that. 

Here is a MWE if I take the data from the Readme and I just remove the 2 last analyses:

```
using Isoplot

# Example U-Pb dataset (MacLennan et al. 2020)
#       207/235  1σ abs   206/238     1σ abs     correlation
data = [1.1009 0.00093576 0.123906 0.00002849838 0.319
        1.1003 0.00077021 0.123901 0.00003531178 0.415
        1.0995 0.00049477 0.123829 0.00002538494 0.434
        1.0992 0.00060456 0.123813 0.00003652483 0.616
        1.1006 0.00071539 0.123813 0.00002228634 0.321
        1.0998 0.00076986 0.123802 0.00002537941 0.418
        1.0992 0.00065952 0.123764 0.00003589156 0.509
        1.0981 0.00109810 0.123727 0.00003959264 0.232
        1.0973 0.00052670 0.123612 0.00002966688 0.470
        1.0985 0.00087880 0.123588 0.00002842524 0.341]

# Turn into UPbAnalysis objects
analyses = UPbAnalysis.(eachcol(data)...,)

# Screen for discordance
ages = age68.(analyses)

wmean(ages; corrected=true)
```
This gives: `(752.26 ± 0.2, 1.963475224992393)` so MSWD of 1.96.
Now, if I do the same thing in IsoplotR I obtain this graph:

Capture d’écran 2024-06-11 à 09 49 19

So an MSWD of 13. This case is of course a bit extreme, but it is just to highlight the difference. I don't know how to use R so this is the output of the GUI, but I made sure to have the options that reflect what we have in Isoplot.jl. On more normally distributed data, the shift will be smaller but Isoplot.jl seems to always have a smaller MSWD. The wmean itself seems to be the same (and I've not activated the external uncertainty propagation in isoplotR, hence the smaller uncertainty).

I tried to look at the R code but I could not figure out what would cause that (and it is quite obscure to me as I don't know the language). Do you have any idea? 
Most of the time, this is not something really problematic as the MSWD is just an indicator, but for my case, I am calculating the long-term variance of my secondary std, and this is based on minimazing the value of MSWD to 1 so this would impact the uncertainty I obtain at the end.

### PR DESCRIPTION
**Pull request by brenhinkeller**
closes #8

### CODE REVIEW

**Comment by brenhinkeller** [comment]
It turned out to be easier than I expected to get the covariance matrix from a vector of correlated `Measurement`s and just use the full matrix method for weighted mean and mswd, so that should work for now

**Comment by brenhinkeller** [comment]
If we want to fully deal with systematic uncertainties in the input ratios, the next step is probably  to use `Measurements.correlated_values` to generate a vector of `Measurement`s for each isotopic ratio that includes the proper covariance structure...

**Comment by Iddingsite** [comment]
Oh wahou, that's really a clean solution. I can confirm that my example now works. Thx for the reactivity! The changes should also be propagated to the function mswd() I assume.

**Comment by Iddingsite** [comment]
> If we want to fully deal with systematic uncertainties in the input ratios, the next step is probably to use `Measurements.correlated_values` to generate a vector of `Measurement`s for each isotopic ratio that includes the proper covariance structure...

That would be neat. But is there not a limit to using Measurements.jl? I thought that linear error propagation theory should not be apply to correlated quantities and/or non-linear functions and we have both here. Or did I miss something?

**Comment by brenhinkeller** [comment]
Should be set as of v0.3.5!

**Pull request merged**
