### PR TITLE
change err name, add rankorder example, import @turbo

### PR DESCRIPTION
**Pull request by Iddingsite**
Hey,

I had a bit of fun with Isoplot (good work!), and made a few changes. Feel free to accept or not the pull request.

I had an error while testing the repo, and it was due to a conflict between LoopVectorization and VectorizedStatistics in the Yorkfit with vsum. So I am just importing @ turbo from LoopVectorization in the main module now, that solved the issue.

Also, I had a conflict with the name err with Base.Exception in Julia. I've renamed the function σ1 and propagated the changes. it shows that you expect σ1 as an input from the user so I think it is a good name, but tell me if you think otherwise.

Finally, I've added in demo.jl a very short example of rankorder plot because I struggled a bit to figure out how it works with variables like analyses (there is only an example in test.jl with fake data to my knowledge).

### CODE REVIEW

**Comment by turbo** [comment]
`@` mentions in commits and issues ping users, consider escaping them

**Comment by Iddingsite** [comment]
> `@` mentions in commits and issues ping users, consider escaping them

oops, sorry for that!

**Comment by brenhinkeller** [comment]
Thanks for the PR! How about maybe `sigma` instead of `σ1`?

**Comment by brenhinkeller** [comment]
(I originally chose `val` and `err` based on the field names in Measurements.jl that they access, but `sigma` would technically be more accurate so I'd be fine with that change, we'll just have to make it a breaking release)

**Comment by brenhinkeller** [comment]
The other other option would be to just not export `val` and `err`

I think I might be missing where the conflict with `Base.Exception` is though -- there's `Base.error` but that's different?

**Comment by Iddingsite** [comment]
> The other other option would be to just not export `val` and `err`
> 
> I think I might be missing where the conflict with `Base.Exception` is though -- there's `Base.error` but that's different?

I actually don't know. When I am importing Isoplot, I have this message:

```julia
using Isoplot
WARNING: using Isoplot.err in module Main conflicts with an existing identifier.
```
And when I use help for err, I only get this:

```julia
No documentation found.

  err is of type Base.ExceptionStack.

  Summary
  ≡≡≡≡≡≡≡≡≡

  struct Base.ExceptionStack
```

and @ which err only show Main.

I would still wish for exporting sigma (or whatever its name) because I found it quite useful to plot with rankorder_plot for example. The problem with sigma is that it is also the name you use for the Metropolis algorithm (and in the test)

**Comment by Iddingsite** [comment]
Otherwise, yeah, maybe there is not need to export it. People can use uncertainty() and value() from Measurements. Maybe reexporting these methods?

**Comment by brenhinkeller** [comment]
Ah that warning could (?) just be that you’ve previously run code in that same REPL that happened to define a variable called `err` (like in a try-catch block perhaps?) 

Unexporting seems good for now -- want to update the PR to do that and then I'll merge it? 

I'm not sure what's causing the code coverage regression, but doesn't seem like anything you did

**Comment by Iddingsite** [comment]
Mmh, 

> Ah that warning could (?) just be that you’ve previously run code in that same REPL that happened to define a variable called `err` (like in a try-catch block perhaps?)
> 
> Unexporting seems good for now -- want to update the PR to do that and then I'll merge it?
> 
> I'm not sure what's causing the code coverage regression, but doesn't seem like anything you did

Mmh, I don't know I just did it in a fresh REPL and I have the same thing. I don't see anything in my startup.jl file that could also be responsable for that.. But if you don't have the same problem, it definitely comes from me. Anyway, I've reverted the changes so I guess it is ready to merge! Thx for your time

**Comment by brenhinkeller** [comment]
Any time, thanks for PRing!

**Pull request merged**
